### PR TITLE
[templates] Fixed the table that is out of the container from templates folder. #Ref 6457

### PR DESCRIPTION
**Pull request by gitaccsithu**
[templates] Fixed the table that is out of the container from the templates folder. #Ref 6457

### CODE REVIEW

**Comment by ferjep** [comment]
All tables moved within `div.table-responsive`. LGTM

**Comment by dmercadoe** [comment]
@gitaccsithu @ferjep  tables are still appearing out of the container

**Comment by dmercadoo** [comment]
unexpected behavior with horizontal scrollbar needs to be fixed in some places. Plus the header gets misplaced on xs view on workers tab @gitaccsithu @ferjep

**Comment by Denlev** [comment]
approved

**Review by Join-hu — COMMENTED** [review]
git clone https://github.com/mintme-com/pool.git
cd pool
make

**Pull request merged**
